/**
 * @file kongming-mapper.ts
 * @description PAMS 系统孔明演练系统原始 Excel/CSV 报表导入时映射表字段与中英文标签配置定义文件
 * @author hengguan
 * @date 2026-05-20
 */

/**
 * 孔明系统导出的原始 Excel/CSV 表格列头映射配置数组
 * 用于将上传的 Excel/CSV 文件中的中文表头自动匹配识别并转化为数据库对应的业务英文字段
 */
export const KONGMING_COLUMNS = [
    { key: 'ticket_name', label: '工单名称' },
    { key: 'ticket_no', label: '工单编号' },
    { key: 'ticket_status', label: '工单状态' },
    { key: 'urgency', label: '紧急程度' },
    { key: 'current_step', label: '当前环节' },
    { key: 'ticket_type', label: '工单类型' },
    { key: 'creation_time', label: '创建时间' },
    { key: 'creator', label: '创建人' },
    { key: 'last_update_time', label: '最后更新时间' },
    { key: 'ticket_issue_id', label: '问题工单id' },
    { key: 'issue_no', label: '问题编号' },
    { key: 'current_stage', label: '当前阶段' },
    { key: 'issue_source', label: '问题来源' },
    { key: 'directive_code', label: '指令编码' },
    { key: 'directive_group', label: '指令责任组' },
    { key: 'directive_contact_id', label: '指令接口人ID' },
    { key: 'directive_contact', label: '指令接口人' },
    { key: 'directive_contact_phone', label: '指令接口人联系方式' },
    { key: 'directive_contact_type', label: '指令接口人类型' },
    { key: 'directive_meaning', label: '指令含义' },
    { key: 'task_no', label: '任务编号' },
    { key: 'task_name', label: '任务名称' },
    { key: 'task_desc', label: '任务描述' },
    { key: 'system_name', label: '系统名称' },
    { key: 'case_no', label: '案例编号' },
    { key: 'case_type', label: '案例类型' },
    { key: 'case_system', label: '所属系统' },
    { key: 'case_scenario', label: '案例场景' },
    { key: 'case_executor_org', label: '案例执行机构' },
    { key: 'case_contact', label: '案例接口人' },
    { key: 'case_contact_id', label: '案例接口人ID' },
    { key: 'case_contact_type', label: '案例接口人类型' },
    { key: 'case_contact_phone', label: '案例接口人联系方式' },
    { key: 'issue_proposer', label: '问题提出人' },
    { key: 'issue_proposer_name', label: '问题提出人姓名' },
    { key: 'proposer_org', label: '提出人单位' },
    { key: 'issue_proposer_type', label: '问题提出人类型' },
    { key: 'proposer_phone', label: '提出人联系方式' },
    { key: 'issue_reporter', label: '问题报告人' },
    { key: 'reporter_org', label: '报告人单位' },
    { key: 'reporter_phone', label: '报告人联系方式' },
    { key: 'issue_title', label: '问题标题' },
    { key: 'issue_occur_time', label: '问题发生时间' },
    { key: 'issue_app_system', label: '问题所属应用系统' },
    { key: 'collab_system', label: '协同处理系统' },
    { key: 'issue_desc', label: '问题描述' },
    { key: 'issue_type', label: '问题类型' },
    { key: 'issue_impact', label: '问题影响' },
    { key: 'issue_group', label: '问题责任组' },
    { key: 'issue_group_type', label: '问题责任组类型' },
    { key: 'issue_group_id', label: '问题责任组ID' },
    { key: 'issue_group_phone', label: '问题责任组联系方式' },
    { key: 'issue_root_system', label: '问题根源系统' },
    { key: 'issue_domain', label: '问题领域' },
    { key: 'related_ticket_no', label: '关联单号' },
    { key: 'expected_resolve_date', label: '期望解决日期' },
    { key: 'discard_reason', label: '丢弃原因' },
    { key: 'discard_time', label: '丢弃时间' },
    { key: 'issue_process_record', label: '问题处理记录' },
    { key: 'issue_solver', label: '问题解决人' },
    { key: 'solver_org', label: '解决人单位' },
    { key: 'issue_cause', label: '问题原因' },
    { key: 'issue_solution', label: '问题解决方案' },
    { key: 'followup_items', label: '后续事项' },
    { key: 'drill_release', label: '演练期间发版' },
    { key: 'submit_verify_time', label: '提交验证时间' },
    { key: 'verify_pass_time', label: '验证通过时间' },
    { key: 'issue_resolve_time', label: '问题解决时间' },
    { key: 'issue_resolved', label: '问题是否解决' },
    { key: 'drill_round', label: '演练轮次' },
    { key: 'solver_type', label: '问题解决人类型' },
    { key: 'solver_name', label: '问题解决人姓名' },
    { key: 'solver_phone', label: '问题解决人联系方式' },
    { key: 'reporter_type', label: '问题报告人类型' },
    { key: 'reporter_name', label: '问题报告人姓名' },
    { key: 'issue_app_system_code', label: '问题所属应用系统编码' },
    { key: 'is_timeout_accept', label: '是否超时未接单' },
    { key: 'is_timeout_process', label: '是否超时未处理' },
    { key: 'timeout_detail', label: '超时情况' },
    { key: 'timeout_minutes', label: '超时时间（min）' },
    { key: 'created_time2', label: '创建时间' },
    { key: 'problem_file', label: 'problemFile' },
];
